"""Account names in Arabic and Hebrew, keyed by ERPNext's English name.

Split from barakat_chart.py so the structure and the wording can be reviewed
separately — the structure is ERPNext's and rarely changes, the wording is ours
and the shop owner may well want it adjusted.

Plain shop language over textbook accounting where the two differ: 'Debtors' is
العملاء (customers), not المدينون; 'Office Rent' is إيجار المحل (the shop's rent),
not إيجار المكتب.

Every name must be unique within its language: an Account docname is
"<account_name> - <abbr>", unique per company, so two accounts collapsing onto
one name would make the second one fail to insert.
"""

NAMES = {
    "Application of Funds (Assets)": {"ar": "الأصول", "he": "נכסים"},
    "Current Assets": {"ar": "الأصول المتداولة", "he": "נכסים שוטפים"},
    "Accounts Receivable": {"ar": "الذمم المدينة", "he": "חובות לקוחות"},
    "Debtors": {"ar": "العملاء", "he": "לקוחות"},
    "Bank Accounts": {"ar": "الحسابات البنكية", "he": "חשבונות בנק"},
    "Cash In Hand": {"ar": "النقد في الصندوق", "he": "מזומן בקופה"},
    "Cash": {"ar": "النقد", "he": "מזומן"},
    "Loans and Advances (Assets)": {"ar": "القروض والسلف", "he": "הלוואות ומקדמות"},
    "Employee Advances": {"ar": "سلف الموظفين", "he": "מקדמות לעובדים"},
    "Securities and Deposits": {"ar": "التأمينات والودائع", "he": "ערבויות ופיקדונות"},
    "Earnest Money": {"ar": "العربون", "he": "עירבון"},
    "Prepaid Expenses": {"ar": "المصاريف المدفوعة مقدماً", "he": "הוצאות מראש"},
    "Short-term Investments": {"ar": "استثمارات قصيرة الأجل", "he": "השקעות לזמן קצר"},
    "Stock Assets": {"ar": "أصول المخزون", "he": "נכסי מלאי"},
    "Stock In Hand": {"ar": "المخزون", "he": "מלאי"},
    "Tax Assets": {"ar": "الأصول الضريبية", "he": "נכסי מס"},
    "Fixed Assets": {"ar": "الأصول الثابتة", "he": "רכוש קבוע"},
    "Capital Equipment": {"ar": "المعدات الرأسمالية", "he": "ציוד הוני"},
    "Electronic Equipment": {"ar": "الأجهزة الإلكترونية", "he": "ציוד אלקטרוני"},
    "Furniture and Fixtures": {"ar": "الأثاث والتجهيزات", "he": "ריהוט וציוד"},
    "Office Equipment": {"ar": "معدات المكتب", "he": "ציוד משרדי"},
    "Plants and Machineries": {"ar": "الآلات والمعدات", "he": "מכונות וציוד"},
    "Buildings": {"ar": "المباني", "he": "מבנים"},
    "Software": {"ar": "البرمجيات", "he": "תוכנה"},
    "Accumulated Depreciation": {"ar": "مجمع الإهلاك", "he": "פחת שנצבר"},
    "CWIP Account": {"ar": "أعمال تحت التنفيذ", "he": "עבודות בביצוע"},
    "Investments": {"ar": "الاستثمارات", "he": "השקעות"},
    "Temporary Accounts": {"ar": "الحسابات المؤقتة", "he": "חשבונות זמניים"},
    "Temporary Opening": {"ar": "الافتتاح المؤقت", "he": "פתיחה זמנית"},
    "Expenses": {"ar": "المصاريف", "he": "הוצאות"},
    "Direct Expenses": {"ar": "المصاريف المباشرة", "he": "הוצאות ישירות"},
    "Stock Expenses": {"ar": "مصاريف المخزون", "he": "הוצאות מלאי"},
    "Cost of Goods Sold": {"ar": "تكلفة البضاعة المباعة", "he": "עלות המכר"},
    "Expenses Included In Asset Valuation": {"ar": "مصاريف ضمن تقييم الأصول", "he": "הוצאות בשווי הנכס"},
    "Expenses Included In Valuation": {"ar": "مصاريف ضمن تقييم المخزون", "he": "הוצאות בשווי המלאי"},
    "Stock Adjustment": {"ar": "تسوية المخزون", "he": "התאמת מלאי"},
    "Indirect Expenses": {"ar": "المصاريف غير المباشرة", "he": "הוצאות עקיפות"},
    "Administrative Expenses": {"ar": "المصاريف الإدارية", "he": "הוצאות הנהלה"},
    "Commission on Sales": {"ar": "عمولات المبيعات", "he": "עמלות מכירה"},
    "Depreciation": {"ar": "الإهلاك", "he": "פחת"},
    "Entertainment Expenses": {"ar": "مصاريف الضيافة", "he": "הוצאות אירוח"},
    "Freight and Forwarding Charges": {"ar": "مصاريف الشحن والنقل", "he": "הוצאות הובלה ומשלוח"},
    "Legal Expenses": {"ar": "المصاريف القانونية", "he": "הוצאות משפטיות"},
    "Marketing Expenses": {"ar": "مصاريف التسويق", "he": "הוצאות שיווק"},
    "Miscellaneous Expenses": {"ar": "مصاريف متنوعة", "he": "הוצאות שונות"},
    "Office Maintenance Expenses": {"ar": "مصاريف صيانة المكتب", "he": "הוצאות אחזקת משרד"},
    "Office Rent": {"ar": "إيجار المحل", "he": "שכר דירה"},
    "Postal Expenses": {"ar": "مصاريف البريد", "he": "הוצאות דואר"},
    "Print and Stationery": {"ar": "الطباعة والقرطاسية", "he": "דפוס ומשרד"},
    "Round Off": {"ar": "تقريب الفواتير", "he": "עיגול"},
    "Salary": {"ar": "الرواتب", "he": "משכורות"},
    "Sales Expenses": {"ar": "مصاريف المبيعات", "he": "הוצאות מכירה"},
    "Telephone Expenses": {"ar": "مصاريف الهاتف", "he": "הוצאות טלפון"},
    "Travel Expenses": {"ar": "مصاريف السفر", "he": "הוצאות נסיעה"},
    "Utility Expenses": {"ar": "فواتير الكهرباء والماء", "he": "חשמל ומים"},
    "Write Off": {"ar": "المبالغ المشطوبة", "he": "מחיקות"},
    "Exchange Gain/Loss": {"ar": "أرباح وخسائر فروق العملة", "he": "הפרשי שער"},
    "Interest Expense": {"ar": "مصاريف الفوائد", "he": "הוצאות ריבית"},
    "Bank Charges": {"ar": "عمولات البنك", "he": "עמלות בנק"},
    "Gain/Loss on Asset Disposal": {"ar": "أرباح وخسائر بيع الأصول", "he": "רווח/הפסד ממכירת נכס"},
    "Impairment": {"ar": "انخفاض قيمة الأصول", "he": "ירידת ערך"},
    "Tax Expense": {"ar": "مصاريف الضرائب", "he": "הוצאות מס"},
    "Income": {"ar": "الإيرادات", "he": "הכנסות"},
    "Direct Income": {"ar": "الإيرادات المباشرة", "he": "הכנסות ישירות"},
    "Sales": {"ar": "المبيعات", "he": "מכירות"},
    "Service": {"ar": "الخدمات", "he": "שירותים"},
    "Indirect Income": {"ar": "الإيرادات غير المباشرة", "he": "הכנסות עקיפות"},
    "Interest Income": {"ar": "إيرادات الفوائد", "he": "הכנסות ריבית"},
    "Interest on Fixed Deposits": {"ar": "فوائد الودائع الثابتة", "he": "ריבית על פיקדונות"},
    "Source of Funds (Liabilities)": {"ar": "الالتزامات", "he": "התחייבויות"},
    "Current Liabilities": {"ar": "الالتزامات المتداولة", "he": "התחייבויות שוטפות"},
    "Accounts Payable": {"ar": "الذمم الدائنة", "he": "חובות לספקים"},
    "Creditors": {"ar": "الموردون", "he": "ספקים"},
    "Payroll Payable": {"ar": "رواتب مستحقة الدفع", "he": "שכר לתשלום"},
    "Accrued Expenses": {"ar": "مصاريف مستحقة", "he": "הוצאות לשלם"},
    "Customer Advances": {"ar": "دفعات مقدمة من العملاء", "he": "מקדמות מלקוחות"},
    "Stock Liabilities": {"ar": "التزامات المخزون", "he": "התחייבויות מלאי"},
    "Stock Received But Not Billed": {"ar": "بضاعة مستلمة غير مفوترة", "he": "מלאי שהתקבל וטרם חויב"},
    "Asset Received But Not Billed": {"ar": "أصول مستلمة غير مفوترة", "he": "נכס שהתקבל וטרם חויב"},
    "Duties and Taxes": {"ar": "الرسوم والضرائب", "he": "מסים ואגרות"},
    "Short-term Provisions": {"ar": "مخصصات قصيرة الأجل", "he": "הפרשות לזמן קצר"},
    "Loans (Liabilities)": {"ar": "القروض", "he": "הלוואות"},
    "Secured Loans": {"ar": "قروض مضمونة", "he": "הלוואות מובטחות"},
    "Unsecured Loans": {"ar": "قروض غير مضمونة", "he": "הלוואות לא מובטחות"},
    "Bank Overdraft Account": {"ar": "السحب على المكشوف", "he": "משיכת יתר"},
    "Non-Current Liabilities": {"ar": "الالتزامات طويلة الأجل", "he": "התחייבויות לזמן ארוך"},
    "Long-term Provisions": {"ar": "مخصصات طويلة الأجل", "he": "הפרשות לזמן ארוך"},
    "Employee Benefits Obligation": {"ar": "التزامات مكافآت الموظفين", "he": "התחייבות לזכויות עובדים"},
    "Equity": {"ar": "حقوق الملكية", "he": "הון עצמי"},
    "Capital Stock": {"ar": "رأس المال", "he": "הון מניות"},
    "Dividends Paid": {"ar": "أرباح موزعة", "he": "דיבידנד ששולם"},
    "Opening Balance Equity": {"ar": "رصيد افتتاحي", "he": "יתרת פתיחה"},
    "Retained Earnings": {"ar": "الأرباح المحتجزة", "he": "עודפים"},
    "Revaluation Surplus": {"ar": "فائض إعادة التقييم", "he": "עודף מהערכה מחדש"},
}
